language: csharp
dist: trusty
sudo: required
mono: latest
install:
  - sudo apt-get update -yqq
  - sudo apt-get install nunit-console -yqq
script:
  - xbuild /p:Configuration=Release Pinta.ImageManipulation.sln
  - nunit-console Pinta.ImageManipulation.UnitTests/bin/Release/Pinta.ImageManipulation.Tests.dll
